import { NexusLocation } from "@document/location"
import type { SpaceConstructor } from "@gen/document/v1/entity/space/v1/space_nexus"
import type { Defaults } from "./default-type"
import { defaultDisplayParams } from "./shared"

const soundDefaults = {
  dispersion: 0.5,
  vaporisation: 0.2,
  brightness: 0,
  metal: 0,
  separation: 1,
  harmonicsCount: 32,
  combFilterAmount: 0,
  combFilterRate: 0.15000000596046448,
  combFilterWidth: 0,
}

export const spaceDefaults: Defaults<SpaceConstructor> = {
  ...defaultDisplayParams,
  displayName: "Space",
  isActive: true,
  microTuning: new NexusLocation(),
  gain: 0.70794,
  stereoDetuneShift: 0,
  tuneSemitones: 0,
  tuneASemitones: 0,
  tuneBSemitones: 0,
  glideMs: 0,
  mixAB: -1,
  lfoMixModulationDepth: 0,
  lfoGainModulationDepth: 0,
  lfoStereoDetuneShiftModulationDepth: 0,
  lfoPanningModulationDepth: 0,
  envelopeMixModulationDepth: 0,
  envelopeTuneModulationDepth: 0,
  envelopeLfoRateModulationDepth: 0,
  envelopeLfoAmountModulationDepth: 0,
  velocityGainModulationDepth: 0,
  velocityMixModulationDepth: 0,
  keyboardMixModulationDepth: 0,
  notePlayModeIndex: 3,
  modulationEnvelopeHasRelease: false,
  lfo: {
    waveformIndex: 1,
    rateNormalized: 0.25,
    phaseOffset: 0,
    isSynced: false,
    doesRetrigger: true,
  },
  amplitudeEnvelope: {
    isSynced: false,
    attackTimeNormalized: 0,
    attackSlopeFactor: -0.5,
    decayTimeNormalized: 0.25,
    decaySlopeFactor: 0.5,
    decayIsLooped: false,
    sustainFactor: 0.5,
    releaseTimeNormalized: 0.25,
    releaseSlopeFactor: 0.5,
  },
  modulationEnvelope: {
    isSynced: false,
    attackTimeNormalized: 0,
    attackSlopeFactor: -0.5,
    decayTimeNormalized: 0.25,
    decaySlopeFactor: 0.5,
    decayIsLooped: false,
    sustainFactor: 0.5,
    releaseTimeNormalized: 0.25,
    releaseSlopeFactor: 0.5,
  },
  soundA: soundDefaults,
  soundB: soundDefaults,
  presetName: "",
}
