import type { SpitfireLabsVst3PluginConstructor } from "@gen/document/v1/entity/spitfire_labs_vst3_plugin/v1/spitfire_labs_vst3_plugin_nexus"
import type { Defaults } from "./default-type"
import { defaultDisplayParams } from "./shared"

export const spitfireLabsVst3PluginDefaults: Defaults<SpitfireLabsVst3PluginConstructor> =
  {
    ...defaultDisplayParams,
    displayName: "Spitfire LABS",
    expression: 0,
    dynamics: 0,
    reverb: 0,
    release: 0,
    tightness: 0,
    vibrato: 0,
    simpleMix: 0,
    stereoPan: 0,
    adsrAttack: 0,
    adsrDecay: 0,
    adsrSustain: 0,
    adsrRelease: 0,
    globalGain: 0,
    globalPan: 0,
    globalTune: 0,
    stereoFlip: 0,
    stereoSpread: 0,
    variation: 0,
    delay: 0,
    amount: 0,
    distortion: 0,
    lushVerb: 0,
    pedalVol: 0,
    pedalDyn: 0,
    length: 0,
    timeMachine: 0,
    stretch: 0,
    softPedal: 0,
    response: 0,
    mallet: 0,
    stopMute: 0,
    direction: 0,
    lowPassFilter: 0,
    portamento: 0,
    generalPurpose1: 0,
    generalPurpose2: 0,
    generalPurpose3: 0,
    generalPurpose4: 0,
    generalPurpose5: 0,
    generalPurpose6: 0,
    generalPurpose7: 0,
    generalPurpose8: 0,
    generalPurpose9: 0,
    speed: 0,
    compression: 0,
    scale: 0,
    depth: 0,
    noiseFx: 0,
    grainSpeed: 0,
    state: new Uint8Array(0),
  }
