/**
 * Sample-insert scenarios for the Nexus Showroom.
 *
 * Each scenario function fetches a pre-uploaded sample by id and inserts
 * it into the open project using a specific combination of
 * `InsertSampleOptions`. Together they cover the use cases tracked in
 * `sample-api.md`, so we can verify the API reads intuitively for each.
 *
 * Why prefetched ids? Uploading + transcoding a sample takes 10s+ on a good
 * connection, which makes the showroom feel slow. The five preset samples
 * under `public/samples/` are pre-uploaded once (see
 * `scripts/upload-presets.ts`) and reused via `client.samples.get(...)`.
 *
 * Layer convention: this file is SDK-only (no DOM access). It is
 * consumed by `src/ui/example-sample-insert.ts`.
 */

import type { AuthenticatedClient, SyncedDocument } from "@audiotool/nexus"
import type { NexusEntity } from "@audiotool/nexus/document"
import { Ticks } from "@audiotool/nexus/utils"

/**
 * Stable sample names for the showroom presets. Generated by
 * `scripts/upload-presets.ts`. Re-run that script if any of these need to
 * be replaced (e.g., if the underlying mp3s change).
 */
export const PRESET_SAMPLE_IDS = {
  "loop-1-bar-120bpm": "samples/fd8fec38-8b32-4a1a-bb45-ef67057d6785",
  "loop-4bar-125bpm-distinct": "samples/c38c72f5-279a-41dd-8d95-52d5dd3829e2",
  "phraser-3bar-130bpm": "samples/79e6449d-1d4e-4928-9f5f-d53ea1706855",
  "pad-ambient": "samples/cdac6380-f275-45f4-90d4-ec604ccd2b26",
  "groovy-120bpm": "samples/8b56be00-d18e-4c2b-bb70-20039892c118",
} as const

export type PresetSampleId = keyof typeof PRESET_SAMPLE_IDS

/** Resolve a preset id → `SampleMeta` via the backend. Throws on error. */
async function getPresetMeta(
  client: AuthenticatedClient,
  presetId: PresetSampleId,
) {
  const meta = await client.samples.get(PRESET_SAMPLE_IDS[presetId])
  if (meta instanceof Error) throw meta
  return meta
}

// -- Scenario insert result ------------------------------------------------

export type ScenarioInsertResult = {
  region: NexusEntity<"audioRegion">
  track: NexusEntity<"audioTrack">
}

// -- Standalone scenarios (no user-picked target) -------------------------

/** A. Just insert a prefetched sample at time 0. */
export async function insertScenarioA(
  client: AuthenticatedClient,
  doc: SyncedDocument,
  displayName?: string,
): Promise<ScenarioInsertResult> {
  const meta = await getPresetMeta(client, "loop-4bar-125bpm-distinct")
  return doc.modify((t) => {
    const region = t.insertSample(meta, { displayName })
    const track = t.entities
      .ofTypes("audioTrack")
      .mustGetEntity(region.fields.track.value.entityId)
    return { region, track }
  })
}

/** B. Same sample as A, but with bpm set so it lands on the beat. */
export async function insertScenarioB(
  client: AuthenticatedClient,
  doc: SyncedDocument,
  displayName?: string,
): Promise<ScenarioInsertResult> {
  const meta = await getPresetMeta(client, "loop-4bar-125bpm-distinct")
  return doc.modify((t) => {
    const region = t.insertSample(meta, { sample: { bpm: 125 }, displayName })
    const track = t.entities
      .ofTypes("audioTrack")
      .mustGetEntity(region.fields.track.value.entityId)
    return { region, track }
  })
}

/** C. Stretch a 2-bar sample to that exact musical duration. */
export async function insertScenarioC(
  client: AuthenticatedClient,
  doc: SyncedDocument,
  displayName?: string,
): Promise<ScenarioInsertResult> {
  const meta = await getPresetMeta(client, "phraser-3bar-130bpm")
  return doc.modify((t) => {
    const region = t.insertSample(meta, {
      sample: { musicDurationTicks: Ticks.Bars(2) },
      displayName,
    })
    const track = t.entities
      .ofTypes("audioTrack")
      .mustGetEntity(region.fields.track.value.entityId)
    return { region, track }
  })
}

/** D. 1-bar sample, looped 4 times. */
export async function insertScenarioD(
  client: AuthenticatedClient,
  doc: SyncedDocument,
  displayName?: string,
): Promise<ScenarioInsertResult> {
  const meta = await getPresetMeta(client, "loop-1-bar-120bpm")
  return doc.modify((t) => {
    const region = t.insertSample(meta, {
      sample: { musicDurationTicks: Ticks.Bars(1) },
      region: { durationTicks: Ticks.Bars(4) },
      loop: true,
      displayName,
    })
    const track = t.entities
      .ofTypes("audioTrack")
      .mustGetEntity(region.fields.track.value.entityId)
    return { region, track }
  })
}

/** F. Unknown-length sample at project bpm, looping until bar 22. */
export async function insertScenarioF(
  client: AuthenticatedClient,
  doc: SyncedDocument,
  displayName?: string,
): Promise<ScenarioInsertResult> {
  const meta = await getPresetMeta(client, "pad-ambient")
  return doc.modify((t) => {
    const region = t.insertSample(meta, {
      sample: { bpm: "project" },
      region: { durationTicks: Ticks.Bars(21) },
      loop: true,
      displayName,
    })
    const track = t.entities
      .ofTypes("audioTrack")
      .mustGetEntity(region.fields.track.value.entityId)
    return { region, track }
  })
}

/** G. Place at bar 2, sample is 120 bpm, loop until bar 7. */
export async function insertScenarioG(
  client: AuthenticatedClient,
  doc: SyncedDocument,
  displayName?: string,
): Promise<ScenarioInsertResult> {
  const meta = await getPresetMeta(client, "loop-1-bar-120bpm")
  return doc.modify((t) => {
    const region = t.insertSample(meta, {
      sample: { bpm: 120 },
      region: {
        positionTicks: Ticks.Bars(1),
        durationTicks: Ticks.Bars(5),
      },
      loop: true,
      displayName,
    })
    const track = t.entities
      .ofTypes("audioTrack")
      .mustGetEntity(region.fields.track.value.entityId)
    return { region, track }
  })
}

/** H. 125 bpm 4-bar sample; loop bars 2-4 of the sample, placed at region
 *     bars 3-6. The `loop.startTicks` also shifts where the sample begins
 *     playing, so the very first instant of the region is bar 2 of the
 *     sample. */
export async function insertScenarioH(
  client: AuthenticatedClient,
  doc: SyncedDocument,
  displayName?: string,
): Promise<ScenarioInsertResult> {
  const meta = await getPresetMeta(client, "loop-4bar-125bpm-distinct")
  return doc.modify((t) => {
    const region = t.insertSample(meta, {
      sample: { bpm: 125 },
      region: {
        positionTicks: Ticks.Bars(2),
        durationTicks: Ticks.Bars(3),
      },
      loop: {
        startTicks: Ticks.Bars(1),
        durationTicks: Ticks.Bars(2),
      },
      displayName,
    })
    const track = t.entities
      .ofTypes("audioTrack")
      .mustGetEntity(region.fields.track.value.entityId)
    return { region, track }
  })
}

// -- Scenarios targeting an existing entity -------------------------------

/** I. Add a new audio track on an existing audio device. The sample lands
 *     on a freshly-created track whose `player` is the chosen device. */
export async function insertScenarioI(
  client: AuthenticatedClient,
  doc: SyncedDocument,
  device: NexusEntity<"audioDevice">,
  displayName?: string,
): Promise<ScenarioInsertResult> {
  const meta = await getPresetMeta(client, "loop-1-bar-120bpm")
  return doc.modify((t) => {
    const region = t.insertSample(meta, { attachTo: device, displayName })
    const track = t.entities
      .ofTypes("audioTrack")
      .mustGetEntity(region.fields.track.value.entityId)
    return { region, track }
  })
}

/** J. Stack a new region onto an existing audio track. No track is
 *     created — the chosen track gains another region. */
export async function insertScenarioJ(
  client: AuthenticatedClient,
  doc: SyncedDocument,
  track: NexusEntity<"audioTrack">,
  displayName?: string,
): Promise<ScenarioInsertResult> {
  const meta = await getPresetMeta(client, "groovy-120bpm")
  return doc.modify((t) => {
    const region = t.insertSample(meta, {
      sample: { bpm: 120 },
      attachTo: track,
      displayName,
    })
    return { region, track }
  })
}

// -- Remove helpers --------------------------------------------------------

/**
 * Remove the audio track (and the region that points at it) that was
 * created by a scenario run. Used for the scenarios that create a new
 * track — A-H and I.
 */
export async function removeScenarioTrack(
  doc: SyncedDocument,
  track: NexusEntity<"audioTrack">,
): Promise<void> {
  await doc.modify((t) => t.removeWithDependencies(track))
}

/**
 * Remove just the region (and its automation events + collection) created
 * by a scenario run, leaving the host track in place. Used for scenario J,
 * where the sample was inserted onto a user-picked existing track.
 *
 * The associated `sample` entity is also removed; it is orphaned once the
 * region is gone.
 */
export async function removeScenarioRegion(
  doc: SyncedDocument,
  region: NexusEntity<"audioRegion">,
): Promise<void> {
  const sampleId = region.fields.sample.value.entityId
  const collectionId = region.fields.playbackAutomationCollection.value.entityId
  await doc.modify((t) => {
    // Removing the automation collection cascades to its events AND to the
    // audio region (both point to the collection), so the track is left
    // intact while the region is unwound.
    t.removeWithDependencies(collectionId)
    // Sample is now orphan — plain remove works.
    t.remove(sampleId)
  })
}

// -- Scenarios catalog -----------------------------------------------------

export type ScenarioId = "A" | "B" | "C" | "D" | "F" | "G" | "H" | "I" | "J"

type ScenarioCommon = {
  id: ScenarioId
  title: string
  description: string
  /** Which preset this scenario uses. Maps to a key of
   *  `PRESET_SAMPLE_IDS` and a filename under `public/samples/<id>.mp3`. */
  presetId: PresetSampleId
  /** The full insert call rendered as text, including the
   *  `client.samples.get(...)` lookup. */
  codeSnippet: string
}

/**
 * Scenario shape:
 *
 * - `kind: "standalone"` — no user input needed. `run` creates everything
 *   from scratch.
 * - `kind: "attach-device"` — the user picks an existing
 *   `audioDevice` and `run` adds a new track + region on it.
 * - `kind: "attach-track"` — the user picks an existing `audioTrack` and
 *   `run` stacks a new region onto it (no new track).
 *
 * `kind` is what the UI switches on to decide whether to render a target
 * picker.
 */
export type Scenario =
  | (ScenarioCommon & {
      kind: "standalone"
      run: (
        client: AuthenticatedClient,
        doc: SyncedDocument,
        displayName?: string,
      ) => Promise<ScenarioInsertResult>
    })
  | (ScenarioCommon & {
      kind: "attach-device"
      run: (
        client: AuthenticatedClient,
        doc: SyncedDocument,
        device: NexusEntity<"audioDevice">,
        displayName?: string,
      ) => Promise<ScenarioInsertResult>
    })
  | (ScenarioCommon & {
      kind: "attach-track"
      run: (
        client: AuthenticatedClient,
        doc: SyncedDocument,
        track: NexusEntity<"audioTrack">,
        displayName?: string,
      ) => Promise<ScenarioInsertResult>
    })

/** Helper to format the code snippet for each scenario uniformly. */
const codeForInsert = (presetId: PresetSampleId, body: string): string => {
  const id = PRESET_SAMPLE_IDS[presetId]
  return `const meta = await client.samples.get(
  "${id}",
)
if (meta instanceof Error) throw meta

await doc.modify((t) => ${body})`
}

/** Variant of {@link codeForInsert} that also shows where the user-picked
 *  attach target comes from. */
const codeForAttach = (
  presetId: PresetSampleId,
  pickerType: "audioDevice" | "audioTrack",
  pickerName: string,
  body: string,
): string => {
  const id = PRESET_SAMPLE_IDS[presetId]
  return `const meta = await client.samples.get(
  "${id}",
)
if (meta instanceof Error) throw meta

// Pick an existing entity from the document — here, the one
// selected in the dropdown to the right.
const ${pickerName}: NexusEntity<"${pickerType}"> = ...

await doc.modify((t) => ${body})`
}

export const SCENARIOS: readonly Scenario[] = [
  {
    id: "A",
    kind: "standalone",
    title: "Just insert",
    description:
      "Drop the same 125 bpm loop with no extra options — listen, then try scenario B.",
    presetId: "loop-4bar-125bpm-distinct",
    codeSnippet: codeForInsert(
      "loop-4bar-125bpm-distinct",
      `t.insertSample(meta)`,
    ),
    run: insertScenarioA,
  },
  {
    id: "B",
    kind: "standalone",
    title: "Same sample, with 125 bpm",
    description:
      "Same clip as scenario A — compare: without bpm it drifts off the grid; with `sample: { bpm: 125 }` it locks to the metronome.",
    presetId: "loop-4bar-125bpm-distinct",
    codeSnippet: codeForInsert(
      "loop-4bar-125bpm-distinct",
      `t.insertSample(meta, {
    sample: { bpm: 125 },
  })`,
    ),
    run: insertScenarioB,
  },
  {
    id: "C",
    kind: "standalone",
    title: "Exactly 2 bars long",
    description:
      "I know the sample is 2 bars long — stretch it to that musical duration, ignoring its real-time length.",
    presetId: "phraser-3bar-130bpm",
    codeSnippet: codeForInsert(
      "phraser-3bar-130bpm",
      `t.insertSample(meta, {
    sample: { musicDurationTicks: Ticks.Bars(2) },
  })`,
    ),
    run: insertScenarioC,
  },
  {
    id: "D",
    kind: "standalone",
    title: "1 bar, looped 4 times",
    description:
      "I know the sample is 1 bar long. Stretch to one bar and let the region run for four bars by looping.",
    presetId: "loop-1-bar-120bpm",
    codeSnippet: codeForInsert(
      "loop-1-bar-120bpm",
      `t.insertSample(meta, {
    sample: { musicDurationTicks: Ticks.Bars(1) },
    region: { durationTicks: Ticks.Bars(4) },
    loop: true,
  })`,
    ),
    run: insertScenarioD,
  },
  {
    id: "F",
    kind: "standalone",
    title: "Native speed, loop until bar 22",
    description:
      "Don't know the sample's bpm — use the project's current bpm and let the region run until bar 22.",
    presetId: "pad-ambient",
    codeSnippet: codeForInsert(
      "pad-ambient",
      `t.insertSample(meta, {
    sample: { bpm: "project" },
    region: { durationTicks: Ticks.Bars(21) },
    loop: true,
  })`,
    ),
    run: insertScenarioF,
  },
  {
    id: "G",
    kind: "standalone",
    title: "Start at bar 2, loop until bar 7",
    description:
      "Place the region at bar 2 and let it loop for five bars. Bar 1 = position 0.",
    presetId: "loop-1-bar-120bpm",
    codeSnippet: codeForInsert(
      "loop-1-bar-120bpm",
      `t.insertSample(meta, {
    sample: { bpm: 120 },
    region: {
      positionTicks: Ticks.Bars(1),
      durationTicks: Ticks.Bars(5),
    },
    loop: true,
  })`,
    ),
    run: insertScenarioG,
  },
  {
    id: "H",
    kind: "standalone",
    title: "Loop a sub-range",
    description:
      "125 bpm, 4-bar sample. Loop bars 2-4 of the sample and place the region at bar 3 through bar 6. `loop.startTicks` also shifts the playback start so bar 2 of the sample plays first.",
    presetId: "loop-4bar-125bpm-distinct",
    codeSnippet: codeForInsert(
      "loop-4bar-125bpm-distinct",
      `t.insertSample(meta, {
    sample: { bpm: 125 },
    region: {
      positionTicks: Ticks.Bars(2),
      durationTicks: Ticks.Bars(3),
    },
    loop: {
      startTicks: Ticks.Bars(1),
      durationTicks: Ticks.Bars(2),
    },
  })`,
    ),
    run: insertScenarioH,
  },
  {
    id: "I",
    kind: "attach-device",
    title: "New track on an existing audio device",
    description:
      "Pick an existing audio device. A fresh audio track is created on it and the sample is dropped onto that track.",
    presetId: "loop-1-bar-120bpm",
    codeSnippet: codeForAttach(
      "loop-1-bar-120bpm",
      "audioDevice",
      "device",
      `t.insertSample(meta, {
    attachTo: device,
  })`,
    ),
    run: insertScenarioI,
  },
  {
    id: "J",
    kind: "attach-track",
    title: "Stack onto an existing audio track",
    description:
      "Pick an existing audio track. The sample is added as another region on that same track — no new track is created.",
    presetId: "groovy-120bpm",
    codeSnippet: codeForAttach(
      "groovy-120bpm",
      "audioTrack",
      "track",
      `t.insertSample(meta, {
    sample: { bpm: 120 },
    attachTo: track,
  })`,
    ),
    run: insertScenarioJ,
  },
]
